### ISSUE TITLE
proposal for subrepos' file format

### ISSUE THREAD

**Issue by charlyoleg2** [jmnavarrol/python-multigit#10]
Hi, thanks for this tool and all your thoughts around git-subrepos, that i'm sharing to 100%.
I'm coding a very similar tool but in javascript called vag (https://github.com/charlyoleg2/vag). Parametrix_vag is an usage example: https://github.com/charlyoleg2/parametrix_vag
As you can see, the yaml listing the subrepos is very similar to your format:
https://github.com/charlyoleg2/parametrix_vag/blob/main/parametrix_repos.yml
The format of Vag is the one used by vcstool (https://github.com/dirk-thomas/vcstool) doing the same job as our tools ;) Even if this tool hasn't been updated for three years, it is widely used because it belongs to the official tool-chain of ROS (https://ros.org/), a very popular robotic framework.
The reason of this message is because I think, it would be great for our users sharing the same format. Conceptually they are already identical. Just few details should be aligned in practice.
What do you think about aligning the format on vcstool?

**Comment by jmnavarrol** [comment]
Hi, [charlyoleg2](https://github.com/charlyoleg2):

Thanks a lot for your kind words about multigit.

First for the TL;DR: while I considered your proposal very interesting, I'm almost completely inclined to consider it a *"won't fix"*, sorry.

Let me explain:
There are technical reasons:
* This is at the moment a *"git-only"* tool, and so it will be for the foreseeable future.  While I worked on the past with RCS, CVS, SVN and a bit of Mercurial, that's not been the case anymore for years and most possibly that will be the case in the future so it doesn't make sense to me to add provisions for different SCMs.  That, on itself, wouldn't be a showstopper, as multigit could accept an optional *"type"* key and yet do nothing with it or, maybe, throw an error in case its value is not *git*.
* *subrepos* data structure is a list while *repositories* is a dictionary.  I thought it that way since I consider it in fact represents a list, a collection of identical structures, and not a collection, a *"list"* of named references.  This way it also has the nice side-effect of being automatically sorted which allows to reference *"deeper"* subrepos after *"higher"* ones (or the other way around if that ever makes sense -not that I have a use case for that).  I already take advantage of that kind of sorting on some of my deployments.

There are also conceptual reasons:
* Back to the dictionary issue: why should it be the key the local path instead of the repository? Yes, the local path is naturally unique while your might want to check out the same repo (at different gitrefs) to different paths, but that could be also expressed by means of a list under the *repository* key.  I think it adds cognitive load for no practical value.
* Version? the *version* key doesn't hold a *"version"*; it holds a remote reference (which I would be inclined to call *"gitref"* in the -again, sole case of Git).  If I'm not already using *gitref* is because I still didn't manage to properly identify the *"true"* nature of a *gitref* in all corner cases: the same short name may reference both a tag or a branch or even technically a commit -while I don't think anybody would be crazy enough to add a tag or a branch to look like a hash.  I could ask for an unambiguous reference, i.e.: refs/tags/a-name vs refs/heads/a-name but, on one hand, that wouldn't be without its own added complexity (now code should check if a slash-separated string references a path within the repository or a symbolic reference, and also it would fail at the main pusher of this project, *"making easy things easy"*, on the other.

As you see, neither of these reasons is unsurmountable on itself but it's my opinion all them together rest my case.

I won't just say *"won't fix"* and done with it, though, as I consider your suggestion to be of interest.  As you'll see in this issue's companion commit, it led me to add entries to my TODO list: I'm more inclined to revisit the *"you should only need to reference a gitref and let the code figure what it means"*, which would simplify the definition yaml.  I'm also more inclined now to split this code into a library and a command line script so others could make use of the *"engine"* while not being tied up to the tool.  This way, any data definition (and/or source file) would be accepted as long as you pass the right data to the library -even myself already have a use case for that (no expected timeline for any of those, tough).

I'm sorry if that's not what you expected; it's not easy to say *"no"* but I honestly feel it to be the right answer.

I'll leave this issue open for a while in case you want to reply.

**Comment by charlyoleg2** [comment]
Thank you for the long answer. And no problem about your decline.
Just few comments:
1. I started also with a list, which is idiomatically more correct in my view. But then move to dictionary to mimic Vcstool
2. Vag also supports only git. Other repo types are just ignored.
3. Type git is the default one (also for Vcstool), so it doesn't have to be mentioned for each repo-entry in the config file 
4. I see also value in the ordered list. Luckily, in Javascript, dictionaries are ordered in alphabetix order of the keys. So nested repo should work.
Enjoy your project and keep fun
